### ISSUE TITLE
what does PAD / GO /  EOS / UNK mean?

### ISSUE THREAD

**Issue by guotong1988** [nicolas-ivanov/tf_seq2seq_chatbot#15]
Thank you !

**Comment by nicolas-ivanov** [comment]
These are the special tokens used in seq2seq:
- `GO` - the same as `<start>` on the picture below - the first token which is fed to the decoder along with the though vector in order to start generating tokens of the answer
- `EOS` - "end of sentence" - the same as `<end>` on the picture below - as soon as decoder generates this token we consider the answer to be complete (you can't use usual punctuation marks for this purpose cause their meaning can be different)
- `UNK` - "unknown token" - is used to replace the rare words that did not fit in your vocabulary. So your sentence `My name is guotong1988` will be translated into `My name is _unk_`.
- `PAD` - your GPU (or CPU at worst) processes your training data in batches and all the sequences in your batch should have the same length. If the max length of your sequence is 8, your sentence `My name is guotong1988` will be padded from either side to fit this length:  `My name is guotong1988 _pad_ _pad_ _pad_ _pad_` 

![image](https://cloud.githubusercontent.com/assets/2272790/18410099/1d0a1c1a-7761-11e6-9fe1-bd2e5622b90a.png)

**Comment by Yangmy2047** [comment]
very clear

**Comment by kumawatdevesh** [comment]
great!

**Comment by vyspi394** [comment]
Awesome !Helped me a lot.

**Comment by ryuryukke** [comment]
Thanks a lot :)

**Comment by aaparikh** [comment]
Thanks for this 👍🏻

**Comment by wendyZhang98** [comment]
Thanks a lot! Really clear to understand!

**Comment by sminjeon** [comment]
Thanks a lot~~
